databases:
  - name: earnminiapp-db
    plan: free
    databaseName: earnminiapp
    user: earnminiapp_user

services:
  # ===== Backend (Go) =====
  - type: web
    name: earnminiapp-backend
    runtime: go
    rootDir: backend
    buildCommand: go build -o server ./cmd/server
    startCommand: ./server
    plan: free
    envVars:
      - key: postgresql://earnminiapp_db_user:0UqeXpQT4tS0un5VQI2c8yX0CX8FfJlm@dpg-datvkhbncjis73a6qikg-a/earnminiapp_db
        fromDatabase:
          name: earnminiapp-db
          property: connectionString
      - key: PORT
        value: 10000

  # ===== Frontend (Static) =====
  - type: web
    name: earnminiapp-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: https://earnminiapp-1.onrender.com
        fromService:
          type: web
          name: earnminiapp-backend
          property: host
